#!/usr/bin/env node
/**
 * Build script to embed default-config.toml as a TypeScript module
 * This makes the config available without file system access at runtime
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.join(__dirname, '..');

// Read the default config
const configPath = path.join(rootDir, 'default-config.toml');
const configContent = fs.readFileSync(configPath, 'utf-8');

// Generate TypeScript module
const output = `// AUTO-GENERATED by scripts/embed-config.js
// Do not edit manually. Source: default-config.toml

/**
 * Default configuration content embedded at build time
 */
export const DEFAULT_CONFIG_CONTENT = \`${escapeTemplateLiteral(configContent)}\`;

/**
 * Parse the embedded default config
 */
export function getDefaultConfigContent(): string {
  return DEFAULT_CONFIG_CONTENT;
}
`;

// Write to src/generated/default-config.ts
const outputDir = path.join(rootDir, 'src', 'generated');
const outputPath = path.join(outputDir, 'default-config.ts');

// Ensure directory exists
fs.mkdirSync(outputDir, { recursive: true });

// Write file
fs.writeFileSync(outputPath, output);

console.log(`✓ Embedded config: ${configPath} → ${outputPath}`);
console.log(`  Size: ${configContent.length} bytes`);

/**
 * Escape content for use in template literal
 */
function escapeTemplateLiteral(str) {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$');
}
